name: Verify

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno check tasks/*.ts

      - run: deno fmt --check

      - run: deno lint

      - run: deno test --allow-net --allow-read --allow-write --allow-env
